name: benvis
description: Benvis Life OS - Flutter App
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.10
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  uuid: ^4.3.3
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  local_auth: ^2.1.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/benevis_icon.png"
  min_sdk_android: 23
