name: android-apk (benvis stable)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "benvis/**"
      - ".github/workflows/android-apk.yml"

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Java 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
        with: { distribution: temurin, java-version: "17" }
      - name: Setup Flutter
        uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225
        with: { channel: "stable", cache: true }
      - name: Cache Gradle
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Cache Pub
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('benvis/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-
      - name: Flutter Doctor
        run: flutter --version && flutter doctor -v
      - name: Pub Get
        working-directory: ./benvis
        run: flutter pub get
      - name: Analyze
        working-directory: ./benvis
        run: flutter analyze
      - name: Build APK (release)
        working-directory: ./benvis
        env: { JAVA_TOOL_OPTIONS: "-Xmx3g -Dfile.encoding=UTF-8" }
        run: |
          flutter build apk --release --split-per-abi || flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: android-apk
          path: benvis/build/app/outputs/flutter-apk/*.apk