name: BENVIS Build & Release

on:
  workflow_dispatch:
    inputs:
      demo:
        description: Enable DEMO_MODE
        required: false
        default: "false"
      versionName:
        description: Build name (e.g., 0.1.3)
        required: false
        default: ""
      buildNumber:
        description: Build number (e.g., 103)
        required: false
        default: ""
  push:
    branches:
      - main
    paths:
      - benvis/**
      - .github/workflows/benvis-build.yml

env:
  PROJECT_DIR: benvis
  JAVA_TOOL_OPTIONS: "-Xmx4g"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.22.0"
          cache: true
      
      - name: Show tool versions
        run: |
          java -version
          flutter --version
          dart --version
      
      - name: Restore Gradle caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      
      - name: Get dependencies (retry)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          for i in 1 2 3; do
            flutter pub get && break || sleep 3
          done
      
      - name: Codegen (optional)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs || echo "No codegen"
      
      - name: Pub report
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter pub outdated || true
      
      - name: Build APK (split-per-abi)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          EXTRA=""
          [ -n "${{ github.event.inputs.versionName }}" ] && EXTRA="$EXTRA --build-name=${{ github.event.inputs.versionName }}"
          [ -n "${{ github.event.inputs.buildNumber }}" ] && EXTRA="$EXTRA --build-number=${{ github.event.inputs.buildNumber }}"
          flutter build apk --release --split-per-abi \
            --dart-define=DEMO_MODE=${{ inputs.demo || 'false' }} $EXTRA
      
      - name: Build AAB (optional)
        working-directory: ${{ env.PROJECT_DIR }}
        continue-on-error: true
        run: |
          EXTRA=""
          [ -n "${{ github.event.inputs.versionName }}" ] && EXTRA="$EXTRA --build-name=${{ github.event.inputs.versionName }}"
          [ -n "${{ github.event.inputs.buildNumber }}" ] && EXTRA="$EXTRA --build-number=${{ github.event.inputs.buildNumber }}"
          flutter build appbundle --release \
            --dart-define=DEMO_MODE=${{ inputs.demo || 'false' }} $EXTRA
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benvis-android-${{ github.run_number }}
          path: |
            ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/*-release.apk
            ${{ env.PROJECT_DIR }}/build/app/outputs/bundle/release/*.aab
            ${{ env.PROJECT_DIR }}/pubspec.yaml
            ${{ env.PROJECT_DIR }}/pubspec.lock
          if-no-files-found: warn
          retention-days: 7
      
      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: benvis-build-${{ github.run_number }}
          name: BENVIS Build #${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/*-release.apk
            ${{ env.PROJECT_DIR }}/build/app/outputs/bundle/release/*.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
