name: BENVIS Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'benvis/**'
      - '.github/workflows/benvis-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.0'

      - name: Fetch dependencies
        working-directory: benvis
        run: flutter pub get

      - name: Build release APKs
        working-directory: benvis
        run: flutter build apk --release --split-per-abi

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benvis-android
          path: benvis/build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error
