name: BENVIS Build
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - benvis/**
      - .github/workflows/benvis-build.yml
env:
  PROJECT_DIR: benvis
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
        with:
          distribution: temurin
          java-version: "17"
      - uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225
        with:
          channel: stable
          flutter-version: "3.22.0"
          cache: true
      - name: Get dependencies
        working-directory: ./benvis
        run: flutter pub get
      - name: Build APK
        working-directory: ./benvis
        run: flutter build apk --release --split-per-abi
      - name: Upload artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: benvis-android
          path: benvis/build/app/outputs/flutter-apk/*.apk
          if-no-files-found: warn