      - name: Install Android SDK (cmdline-tools + API 35 + build-tools 35)
        run: |
          set -euxo pipefail
          mkdir -p "$ANDROID_SDK_ROOT"/cmdline-tools
          curl -L -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q cmdtools.zip -d "$ANDROID_SDK_ROOT"/cmdline-tools
          mv "$ANDROID_SDK_ROOT"/cmdline-tools/cmdline-tools "$ANDROID_SDK_ROOT"/cmdline-tools/latest
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/35.0.0" >> $GITHUB_PATH

          # --- حل خطای "yes: standard output: Broken pipe" ---
          # sdkmanager گاهی زود خروجی را می‌بندد و با pipefail کل استپ می‌ریزد.
          # موقتاً pipefail را خاموش می‌کنیم، لایسنس‌ها را می‌پذیریم، بعد دوباره روشن می‌کنیم.
          set +o pipefail
          yes | "$ANDROID_SDK_ROOT"/cmdline-tools/latest/bin/sdkmanager --licenses >/dev/null
          set -o pipefail

          "$ANDROID_SDK_ROOT"/cmdline-tools/latest/bin/sdkmanager --install \
            "platform-tools" "platforms;android-35" "build-tools;35.0.0"
