name: Build Android (BENVIS – no actions)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'benvis/**'
      - '.github/workflows/build-android.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: benvis
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      PATH: /usr/lib/jvm/java-17-openjdk-amd64/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/lib/android/sdk/platform-tools:/usr/local/lib/android/sdk/cmdline-tools/latest/bin:/usr/local/lib/android/sdk/build-tools/34.0.0:/home/runner/work/flutter/bin

    steps:
      # 0) کلون ریپو بدون اکشن checkout
      - name: Checkout (no action)
        run: |
          set -e
          git init .
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git fetch --depth=1 origin ${{ github.ref_name }}
          git checkout FETCH_HEAD

      # 1) پیش‌نیازهای سیستم
      - name: Install system deps (JDK, tools)
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk wget unzip xz-utils zip libglu1-mesa curl git

      # 2) نصب Android SDK (cmdline-tools + platform + build-tools)
      - name: Install Android SDK
        run: |
          set -e
          sudo mkdir -p $ANDROID_HOME
          sudo chown -R $USER:$USER $ANDROID_HOME
          cd /tmp
          # دریافت آخرین commandlinetools (alias