name: Build Android (BENVIS)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'benvis/**'
      - '.github/workflows/build-android.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: |
          cd benvis
          flutter pub get

      - name: Build APK
        run: |
          cd benvis
          flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: benvis-apk
          path: benvis/build/app/outputs/flutter-apk/*.apk